site_name: Collaborative Cookbook
site_description: A community-driven cookbook built with love and open source.
site_author: Your Name
site_url: https://harshi2410.github.io/collab-cookbook/

theme:
  name: material
  palette:
    # Light mode (default)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red        # Warm, food-friendly
      accent: amber
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: amber
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest

# Custom favicon (optional)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/harshi2410/collab-cookbook

# Keep your nav structure
nav:
  - Home: index.md
  - Indian:
    - Paneer Tikka: recipes/indian/paneer-tikka.md
    - Tandoori Chaap: recipes/indian/tandoori-chaap.md
    - Pav Bhaji: recipes/indian/pav-bhaji.md
    - Chole Kulche: recipes/indian/chole-kulche.md
    - Masala Bhat: recipes/indian/masala-bhat.md
  - Desserts:
    - Brownies: recipes/desserts/brownies.md
    - Rasmalai: recipes/desserts/rasmalai.md
    - Gulab Jamun: recipes/desserts/gulab-jamun.md
    - Rabdi: recipes/desserts/rabdi.md

plugins:
  - search